version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    networks:
      - botnet
    env_file:
      - ".env.dist"
    depends_on:
      - db

  db:
    image: sameersbn/postgresql:10-2
    container_name: database
    restart: always
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql

networks:
  botnet:
    driver: bridge