{
 "title": "Панель Бота",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Новых пользователей (сегодня)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(telegram_id) AS \"Пользователей\"\nFROM users\nWHERE\n  $__timeFilter(created_at) AND\n  created_at >= NOW() - INTERVAL '1 DAYS'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Новых пользователей (сегодня)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(*) AS \"Пользователей\"\nFROM users\nWHERE\n  created_at >= NOW() - INTERVAL '1 DAYS'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Взаимодействия пользователей",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_full_name",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "full_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bot_statistics",
     "select": [
      [
       { "params": [ "event" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Новые пользователи бота",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m),\n  first_name AS \"Имя\",\n  username AS \"Username\"\nFROM users\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1, first_name, username\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Язык (по взаимодействиям)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Язык: $tag_language_code",
     "groupBy": [
      { "params": [ "language_code" ], "type": "tag" }
     ],
     "measurement": "bot_statistics",
     "select": [
      [
       { "params": [ "event" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Взаимодействия с ботом",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "$tag_intent",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "intent" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bot_statistics",
     "select": [
      [
       { "params": [ "event" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "error", "operator": "=", "value": "None" }
     ]
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 16 },
   "targets": [
    {
     "alias": "$tag_error",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "error" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bot_statistics",
     "select": [
      [
       { "params": [ "event" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "error", "operator": "!=", "value": "None" }
     ]
    }
   ]
  }
 ]
}